name: merchants_training
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:  # Replaced flutter_localization
    sdk: flutter
  flutter_svg: ^2.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Or list specific files

  fonts:
    - family: bukra
      fonts:
        - asset: assets/fonts/29ltbukrabold.ttf
          weight: 700
        - asset: assets/fonts/29ltbukraregular.ttf
          weight: 400